version: "3.9"

services:
  # App service
  app-service:
    build: .
    image: app-service
    container_name: app-service
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_URL=
      - JWT_SECRET=

    networks:
      - app-container-network

networks:
  app-container-network:
    name: app-container-network
    driver: bridge
